name: Auto Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Cache dev dependencies
        uses: actions/cache@v4
        with:
          path: .cache/node_modules.tar.gz
          key: ${{ runner.os }}-devdeps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-devdeps-
      - run: npm ci
      - run: npm run auto
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: 'chore(auto): automated task update'
