name: Memory Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run mem-rotate
      - run: npm run commitlog
      # clean up old lock files before committing
      - run: ts-node scripts/clean-locks.ts
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: 'chore(memory): weekly log rotation'
