name: Memory Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Cache dev dependencies
        uses: actions/cache@v4
        with:
          path: .cache/node_modules.tar.gz
          key: ${{ runner.os }}-devdeps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-devdeps-
      - run: npm ci
      - run: ts-node scripts/memory-json.ts
      - run: ts-node scripts/snapshot-json.ts
      - run: mkdir pages && mv memory.json snapshot.json pages/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
